version: 0.2
phases:
  install:
    commands:
      - echo Restore started on `date`
      - 'dotnet restore'
      - echo Restore completed on `date`
  build:
    commands:
      - echo Build started  on `date`
      - 'dotnet build -c Release OpenApiNetCore/OpenApiNetCore.csproj'
      - 'dotnet publish -c Release OpenApiNetCore/OpenApiNetCore.csproj'
      - 'zip OpenApiNetCore/bin/Release/netcoreapp1.0/OpenApiNetCore.zip OpenApiNetCore/bin/Release/netcoreapp1.0/publish/*'
      - aws s3 cp OpenApiNetCore/bin/Release/netcoreapp1.0/OpenApiNetCore.zip s3://$S3_BUCKET/OpenApiNetCore.zip
      - cp template.yaml OpenApiNetCore/bin/Release/netcoreapp1.0/publish/template.yaml
      - cd OpenApiNetCore/bin/Release/netcoreapp1.0/publish/
      - aws cloudformation package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file template-export.yaml
      - cd ../../../../../
      - cp OpenApiNetCore/bin/Release/netcoreapp1.0/publish/template-export.yaml template-export.yaml
artifacts:
  type: zip
  files:
    - template-export.yaml
