version: 0.2
phases:
  install:
    commands:
      - pip install --upgrade awscli
      - echo Restore started on `date`
      - 'dotnet restore'
      - echo Restore completed on `date`
  build:
    commands:
      - echo Build started  on `date`
      - 'dotnet build -c Release OpenApiNetCore/OpenApiNetCore.csproj'
      - 'dotnet publish -c Release OpenApiNetCore/OpenApiNetCore.csproj'
      #- 'zip OpenApiNetCore/bin/Release/netcoreapp1.0/OpenApiNetCore.zip OpenApiNetCore/bin/Release/netcoreapp1.0/publish/*'
      - cp template.yml OpenApiNetCore/bin/Release/netcoreapp1.0/publish/template.yml
      - cd OpenApiNetCore/bin/Release/netcoreapp1.0/publish/
      - ls -las
      - aws cloudformation package --template-file template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
      - cd ../../../../../
      - ls -las
      - cp OpenApiNetCore/bin/Release/netcoreapp1.0/publish/template-export.yml template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
