AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PlayersAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Player API
      Description: A demo API for Player management
      Body:
        swagger: '2.0'
        info:
          title: Player API
          description: A simple API for Player resources
          version: 1.0.1
          contact:
            name: Kevin Sookocheff
            url: https://sookocheff.com
            email: kevin@sookocheff.com
          license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html
          termsOfService: http://sookocheff.com/terms
        paths:
          "/v1/Applicant/{proxy+}":
            get:
              description: Returns a Player resource
              produces:
              - application/json
              responses:
                '200':
                  description: A player resource.
                  schema:
                    "$ref": "#/definitions/Player"
              x-amazon-apigateway-integration:
                type: http
                responses:
                  default:
                    statusCode: '200'
                httpMethod: GET
                uri: http://api.example.com
            parameters:
            - name: id
              in: path
              description: Identifier of player to retreive
              required: true
              type: string
        definitions:
          Player:
            type: object
            properties:
              playerId:
                type: string
              alias:
                type: string
              displayName:
                type: string
              profilePhotoUrl:
                type: string
            required:
            - playerId
            - alias