AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  OpenAPIApplicantLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: OpenApiNetCore::OpenApiNetCore.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore1.0
      MemorySize: 256
      Timeout: 30
      Input:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref OpenAPIApplicantApi
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref OpenAPIApplicantApi
            Path: /{proxy+}
            Method: ANY
  
  OpenAPIApplicantApi:
      Type: AWS::Serverless::Api
      Properties:
        DefinitionUri: s3://ca.amit.version.test/swagger.yml
        StageName: Ravish
        Variables:
          # NOTE: Before using this template, replace the <<region>> and <<account>> fields
          #       in Lambda integration URI in the swagger file to region and accountId 
          #       you are deploying to
          LambdaFunctionName: !Ref OpenAPIApplicantLambda

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref OpenAPIApplicantApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod'